version: '3'

services:
  web:
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8080"
    container_name: music_service
    volumes:
      - .:/music_service
    ports:
      - "127.0.0.1:8080:8080"
